require('./ensure-bun');
const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const srcDir = path.join(rootDir, 'src');
const srcComponentsDir = path.join(srcDir, 'components');
const srcCssPath = path.join(srcDir, 'ogulcan-ui.css');
const srcBundlePath = path.join(srcDir, 'ogulcan-ui.js');
const srcManifestPath = path.join(srcDir, 'components.json');
const srcManifestJsPath = path.join(srcDir, 'components-manifest.js');
const distDir = path.join(rootDir, 'dist');
const distBundlePath = path.join(distDir, 'ogulcan-ui.js');
const distCssPath = path.join(distDir, 'ogulcan-ui.css');
const distManifestPath = path.join(distDir, 'components.json');
const distManifestJsPath = path.join(distDir, 'components-manifest.js');
const publicOgulcanDir = path.join(rootDir, 'ogulcan');
const publicOgulcanJsPath = path.join(publicOgulcanDir, 'ogulcan.js');
const publicOgulcanCssPath = path.join(publicOgulcanDir, 'ogulcan.css');
const srcBankPath = path.join(srcDir, 'ogulcan-bank.js');
const distBankPath = path.join(distDir, 'ogulcan-bank.js');

function readUtf8(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function writeUtf8(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
}

function getComponentFolders() {
  if (!fs.existsSync(srcComponentsDir)) {
    console.error('Error: Components directory not found.');
    process.exit(1);
  }

  return fs.readdirSync(srcComponentsDir)
    .filter((file) => fs.statSync(path.join(srcComponentsDir, file)).isDirectory())
    .sort();
}

function buildBundle(folders) {
  let bundledJs = `/**
 * OgulcanUI Consolidated Library (100% Vanilla Static Offline Bundle)
 * Automatically generated by compile builder on ${new Date().toISOString()}.
 * Runs natively on local filesystem file:// protocol without servers or node_modules.
 */
`;

  const chartNamesPath = path.join(srcDir, 'lib/chart-display-names.js');
  if (fs.existsSync(chartNamesPath)) {
    bundledJs += `\n// ==========================================\n// Chart display names (catalog labels)\n// ==========================================\n`;
    bundledJs += `${readUtf8(chartNamesPath).trim()}\n`;
  }

  const chartEnginePath = path.join(srcDir, 'lib/chart-visual-engine.js');
  if (fs.existsSync(chartEnginePath)) {
    bundledJs += `\n// ==========================================\n// Chart visual engine (50 unique painters)\n// ==========================================\n`;
    bundledJs += `${readUtf8(chartEnginePath).trim()}\n`;
  }

  let compiledCount = 0;

  folders.forEach((folder) => {
    const compDir = path.join(srcComponentsDir, folder);
    const jsPath = path.join(compDir, 'index.js');
    const cssPath = path.join(compDir, 'index.css');
    const htmlPath = path.join(compDir, 'index.html');

    if (!fs.existsSync(jsPath)) {
      console.warn(`Warning: missing index.js in ${folder}. Skipping.`);
      return;
    }

    let jsContent = readUtf8(jsPath);
    const cssContent = fs.existsSync(cssPath) ? readUtf8(cssPath).trim() : '';
    const htmlContent = fs.existsSync(htmlPath) ? readUtf8(htmlPath).trim() : '';

    jsContent = jsContent.replace(/\bexport\s+class\s+/, 'class ');
    jsContent = jsContent.replace(/\/\*\s*\[style\.css\]\s*\*\//g, () => cssContent);
    jsContent = jsContent.replace(/<!--\s*\[template\.html\]\s*-->/g, () => htmlContent);

    bundledJs += `\n// ==========================================\n// Component: ${folder}\n// ==========================================\n`;
    bundledJs += `${jsContent}\n`;
    compiledCount++;
  });

  return { bundledJs, compiledCount };
}

function writeManifests(folders) {
  const manifestJson = `${JSON.stringify(folders, null, 2)}\n`;
  const manifestJs = `/** Auto-generated by build.js - ${folders.length} components */\nwindow.OGULCAN_UI_MANIFEST = ${JSON.stringify(folders)};\n`;

  writeUtf8(srcManifestPath, manifestJson);
  writeUtf8(distManifestPath, manifestJson);
  writeUtf8(srcManifestJsPath, manifestJs);
  writeUtf8(distManifestJsPath, manifestJs);
}

function build() {
  console.log('Starting enterprise bundle build...');

  const folders = getComponentFolders();
  const { bundledJs, compiledCount } = buildBundle(folders);
  const cssBundle = readUtf8(srcCssPath);

  fs.mkdirSync(distDir, { recursive: true });

  writeUtf8(srcBundlePath, bundledJs);
  writeUtf8(distBundlePath, bundledJs);
  writeUtf8(distCssPath, cssBundle);
  writeUtf8(publicOgulcanJsPath, bundledJs);
  writeUtf8(publicOgulcanCssPath, cssBundle);
  writeManifests(folders);

  if (fs.existsSync(srcBankPath)) {
    const bankJs = readUtf8(srcBankPath);
    writeUtf8(distBankPath, bankJs);
    console.log(`Bank loader: ${distBankPath}`);
  } else {
    console.warn('Warning: src/ogulcan-bank.js missing; dist/ogulcan-bank.js not written.');
  }

  console.log(`Built ${compiledCount} components.`);
  console.log(`Bundle: ${distBundlePath}`);
  console.log(`Styles: ${distCssPath}`);
  console.log(`Manifest: ${distManifestPath}`);
  console.log(`Static download: ${publicOgulcanJsPath}`);
}

build();
